# `Detecting Fraud Notes using Keras`

In [101]:
import numpy as np
from numpy import genfromtxt

In [102]:
data = genfromtxt("../DATA/bank_note_data.txt", delimiter=",")

In [103]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

## Separating labels and features

In [104]:
labels = data[:, 4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [105]:
features = data[:, :4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [106]:
X = features
y = labels

## Splitting data into train and test sets

In [107]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.33,
                                                    random_state=42)

In [108]:
len(X_train)

919

## Scaling Data

In [109]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [110]:
scaled_X_train.max()

1.0000000000000002

In [111]:
scaled_X_train.min()

0.0

## Building the model

In [112]:
from keras.models import Sequential
from keras.layers import Dense

### Model Architecture

In [113]:
model = Sequential()

model.add(Dense(4, input_dim=4, activation="relu")) #? input_dim: The number of features

model.add(Dense(8, activation="relu"))

model.add(Dense(1, activation="sigmoid"))

### Compiling the model

In [114]:
model.compile(loss="binary_crossentropy",
              optimizer="adam",
              metrics=["accuracy"])

### Training the model

In [115]:
model.fit(scaled_X_train,
          y_train,
          epochs=50,
          verbose=2)

Epoch 1/50
29/29 - 1s - loss: 0.6888 - accuracy: 0.4995 - 547ms/epoch - 19ms/step
Epoch 2/50
29/29 - 0s - loss: 0.6817 - accuracy: 0.6126 - 38ms/epoch - 1ms/step
Epoch 3/50
29/29 - 0s - loss: 0.6740 - accuracy: 0.6181 - 31ms/epoch - 1ms/step
Epoch 4/50
29/29 - 0s - loss: 0.6671 - accuracy: 0.6322 - 32ms/epoch - 1ms/step
Epoch 5/50
29/29 - 0s - loss: 0.6610 - accuracy: 0.6757 - 30ms/epoch - 1ms/step
Epoch 6/50
29/29 - 0s - loss: 0.6551 - accuracy: 0.6888 - 31ms/epoch - 1ms/step
Epoch 7/50
29/29 - 0s - loss: 0.6490 - accuracy: 0.7062 - 30ms/epoch - 1ms/step
Epoch 8/50
29/29 - 0s - loss: 0.6428 - accuracy: 0.7127 - 27ms/epoch - 940us/step
Epoch 9/50
29/29 - 0s - loss: 0.6367 - accuracy: 0.7193 - 29ms/epoch - 987us/step
Epoch 10/50
29/29 - 0s - loss: 0.6304 - accuracy: 0.7225 - 30ms/epoch - 1ms/step
Epoch 11/50
29/29 - 0s - loss: 0.6241 - accuracy: 0.7291 - 33ms/epoch - 1ms/step
Epoch 12/50
29/29 - 0s - loss: 0.6177 - accuracy: 0.7367 - 31ms/epoch - 1ms/step
Epoch 13/50
29/29 - 0s - loss: 

## Evaluating the model

In [116]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")
predictions

15/15 [==============================] - 0s 1ms/step


array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [117]:
model.metrics_names

['loss', 'accuracy']

In [118]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, predictions))
print()
print(classification_report(y_test, predictions))

[[249   8]
 [ 17 179]]

              precision    recall  f1-score   support

         0.0       0.94      0.97      0.95       257
         1.0       0.96      0.91      0.93       196

    accuracy                           0.94       453
   macro avg       0.95      0.94      0.94       453
weighted avg       0.95      0.94      0.94       453



## Saving the Model

In [119]:
model.save("mymodel.h5")

## Loading the Model

In [120]:
from tensorflow import keras
new_model = keras.models.load_model("mymodel.h5")

In [121]:
predictions = (new_model.predict(scaled_X_test) > 0.5).astype("int32")
predictions

15/15 [==============================] - 0s 1ms/step


array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    