In [184]:
import numpy as np

In [185]:
lst = [1,2,3]
type(lst)

list

## `np.array()`

In [186]:
numpy_arr = np.array(lst)
numpy_arr

array([1, 2, 3])

In [187]:
type(numpy_arr)

numpy.ndarray

## `np.arange()`

In [188]:
np.arange(0,10,3)

array([0, 3, 6, 9])

## `np.zeros()`

In [189]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [190]:
type(0)

int

In [191]:
type(0.)

float

## `np.ones()`

In [192]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## `np.random.seed(101)`

In [193]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [194]:
arr2 = np.random.randint(0, 100, 10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

## `arr.max()`

In [195]:
arr.max()

95

## `arr.min()`

In [196]:
arr.min()

9

## `arr.argmax()`

In [197]:
arr.argmax()

0

## `arr.argmin()`

In [198]:
arr.argmin()

7

## `arr.mean()`

In [199]:
arr.mean()

60.8

## `arr.shape()`

In [200]:
arr.shape

(10,)

## `arr.reshape()`

In [201]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [202]:
# arr.reshape(2,6) # Error

## Accessing Elements

In [203]:
mat = np.arange(0, 100).reshape(10, 10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Method 1: Old

In [204]:
mat[1][1]

11

### Method 2: Better

In [205]:
mat[1, 1]

11

# `Slicing`

## Grabbing all rows for a particular range of columns

In [206]:
mat[:, 0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Grabbing all columns for a particular range of rows

In [207]:
mat[1:4, :]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

## Changing matrix values using slicing

In [208]:
mat[0:3, 0:4] = 0
mat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
mat2 = mat.copy() # Deep copy
mat2[:, :] = 0

In [210]:
mat2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [211]:
mat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])